# net10g MAC/PCS file list (packages first). Build scripts expand $(ROOT).
$(ROOT)/hw/rtl/net10g/eth10g_crc_pkg.sv
$(ROOT)/hw/rtl/net10g/eth10g_pcs_pkg.sv
$(ROOT)/hw/rtl/net10g/eth10g_crc32_64.sv
$(ROOT)/hw/rtl/net10g/eth10g_mac_tx.sv
$(ROOT)/hw/rtl/net10g/eth10g_mac_rx.sv
$(ROOT)/hw/rtl/net10g/eth10g_encode.sv
$(ROOT)/hw/rtl/net10g/eth10g_decode.sv
$(ROOT)/hw/rtl/net10g/eth10g_scrambler.sv
$(ROOT)/hw/rtl/net10g/eth10g_descrambler.sv
$(ROOT)/hw/rtl/net10g/eth10g_tx_gearbox.sv
$(ROOT)/hw/rtl/net10g/eth10g_rx_gearbox.sv
$(ROOT)/hw/rtl/net10g/eth10g_block_lock.sv
$(ROOT)/hw/rtl/net10g/eth10g_ber_monitor.sv
$(ROOT)/hw/rtl/net10g/eth10g_fault_monitor.sv
$(ROOT)/hw/rtl/net10g/eth10g_rx_sequence.sv
$(ROOT)/hw/rtl/net10g/eth10g_tx_reconcile.sv
$(ROOT)/hw/rtl/net10g/eth10g_pcs_tx.sv
$(ROOT)/hw/rtl/net10g/eth10g_pcs_rx.sv
$(ROOT)/hw/rtl/net10g/eth10g_mac_pcs.sv
